workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 120
    environment:
      vars:
        # Déclarer les variables (ex: versionCode)
    scripts:
      - name: Build APK
        script: |
          cd android
          ./gradlew bundleRelease  # Génère l'APK
    artifacts:
      - "android/app/build/outputs/**/*.apk"
